services:
  app:
    image: "webapp"
    ports:
      - 3000:3000
    volumes:
      - db_volume:/data/db
    environment:
      - MYSQL_URL=mysql://user:password@database:3306
    depends_on:
      - database
  database:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=animals
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306

volumes:
  db_volume:
